[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Avnir Models"
authors = [{name = "Avnir", email = "guillaume.theaud.chum@ssss.gouv.qc.ca"}]
dynamic = ["version", "description"]
